@startuml
'https://plantuml.com/sequence-diagram

autonumber

用户->程序:调用/启动
activate 程序
程序->服务器:判断当前cookie是否有效
activate 服务器
程序<--服务器:返回结果
destroy 服务器
程序->服务器:获取一整层楼的座位信息
activate 服务器
程序<--服务器:返回座位信息
destroy 服务器
程序->服务器:发送选座请求
activate 服务器
程序<--服务器:返回结果
destroy 服务器
用户<--程序:结束
destroy 程序
@enduml