@startuml
'https://plantuml.com/sequence-diagram

autonumber

用户->程序:调用/启动
activate 程序
程序->服务器:判断当前cookie是否有效
activate 服务器
程序<--服务器:返回结果
destroy 服务器
程序->服务器:发送请求获取SToken
activate 服务器
程序<--服务器:返回SToken
destroy 服务器
程序->服务器:发送退座请求
activate 服务器
程序<--服务器:返回结果
destroy 服务器
用户<--程序:结束
destroy 程序
@enduml