@startuml
'https://plantuml.com/sequence-diagram

autonumber

用户->程序:调用/启动
程序->服务器:判断当前cookie是否有效
程序<--服务器:返回结果
程序->服务器:获取当前步骤以及排队链接
程序<--服务器:返回结果
程序->服务器:websocket连接，通知服务器排队
程序->服务器:询问排队人数
程序<--服务器:返回排队人数
程序->服务器:获取楼层数据
程序<--服务器:返回楼层数据
程序->服务器:预定座位
程序<--服务器:返回结果
程序->服务器:关闭websocket连接
用户<--程序:结束
@enduml