@startuml
'https://plantuml.com/sequence-diagram

autonumber

用户->程序:调用/启动
activate 程序
程序->服务器:判断当前cookie是否有效
activate 服务器
程序<--服务器:返回结果
destroy 服务器
程序->服务器:获取当前步骤以及排队链接
activate 服务器
程序<--服务器:返回结果
destroy 服务器
程序->服务器:websocket连接，通知服务器排队
activate 服务器
程序->服务器:询问排队人数
activate 服务器
程序<--服务器:返回排队人数
destroy 服务器
程序->服务器:获取楼层数据
activate 服务器
程序<--服务器:返回楼层数据
destroy 服务器
程序->服务器:预定座位
activate 服务器
程序<--服务器:返回结果
destroy 服务器
程序->服务器:关闭websocket连接
destroy 服务器
用户<--程序:结束
destroy 程序
@enduml